params:
- dvclive/params.yaml
metrics:
- dvclive/metrics.json
plots:
- dvclive/plots/metrics:
    x: step
artifacts:
  transformer_model:
    path: models/transformer_model.pth
    type: model
stages:
  train:
    cmd: python train.py
    deps:
    - data/raw
    - train.py
    params:
    - base
    - train
    outs:
    - models/model.pth
